version: '3'

networks:
  inception:
    name: inception
    driver: bridge

services:

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    networks:
      - inception
    env_file: env/wordpress.env
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    networks:
      - inception
    env_file: env/mariadb.env
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ubuntu/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ubuntu/data/mariadb