version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./VueJS
      dockerfile: Dockerfile.dev  # your dev Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./VueJS:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    restart: always