version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./VueJS
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
  proxy:
    container_name: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      proxy:
        condition: service_healthy
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw