---
- hosts: all
  become: true
  tasks:
    - name: Copy app source files
      ansible.builtin.copy:
        src: ../server/
        dest: /home/ubuntu/server/
    - name: Rename init conf
      ansible.builtin.copy:
        remote_src: true
        src: ./server/nginx/proxy-init.conf
        dest: ./server/nginx/proxy.conf
    - name: Launch Nginx Server for init
      community.docker.docker_compose_v2:
        project_src: ./server/
        files: docker-compose.yml
        build: always
        remove_orphans: true
    - name: Launch Certbot
      community.docker.docker_compose_v2_run:
        service: certbot
        project_src: ./server/
        files: docker-compose.yml
        argv:
          - certonly
          - --webroot
          - --webroot-path=/var/www/certbot/
          - --email=arthurascedu@proton.me
          - --agree-tos
          - --no-eff-email
          - -d
          - apgolf.xyz
        cleanup: true
    - name: Rename final conf
      ansible.builtin.copy:
        remote_src: true
        src: ./server/nginx/proxy-final.conf
        dest: ./server/nginx/proxy.conf
    - name: Restart app
      community.docker.docker_compose_v2:
        project_src: ./server/
        files: docker-compose.yml
        build: always
        state: restarted