---
- hosts: all
  become: true
  tasks:
    # - name: "[DEBUG] Stop Inception and remove volumes"
    #   community.docker.docker_compose_v2:
    #     project_src: ./srcs/
    #     files: docker-compose.yml
    #     state: absent
    #     remove_images: all
    #     remove_orphans: true
    #     remove_volumes: true
    # - name: "[DEBUG] Remove old files"
    #   ansible.builtin.file:
    #     path: '/home/ubuntu/{{ item }}'
    #     state: absent
    #   loop:
    #     - data
    #     - srcs
    - name: Copy Inception source files
      ansible.builtin.copy:
        src: ../srcs/
        dest: /home/ubuntu/srcs/
        force: true
    - name: Create volumes directories
      ansible.builtin.file:
        path: '/home/ubuntu/data/{{ item }}'
        state: directory
        recurse: true
        mode: '0755'
      loop:
        - mariadb
        - wordpress
    - name: Launch Inception
      community.docker.docker_compose_v2:
        project_src: ./srcs/
        files: docker-compose.yml
        build: always