---
- hosts: all
  become: true
  tasks:
    - name: Copy VueJS app source files
      ansible.builtin.copy:
        src: ../server/
        dest: /home/ubuntu/server/
    # - name: Create volumes directories
    #   ansible.builtin.file:
    #     path: '/home/ubuntu/data/{{ item }}'
    #     state: directory
    #     recurse: true
    #     mode: '0755'
    #   loop:
    #     - mariadb
    #     - wordpress
    - name: Launch VueJS App
      community.docker.docker_compose_v2:
        project_src: ./server/
        files: docker-compose.yml